// src/generators/angular-generator.ts
import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const _logger = createLogger('angular-generator');

/**
 * Angular Generator - Generates Angular components and projects
 */
export class AngularGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  generateProject(
    projectName: string,
    _architecture: Architecture,
    _stateManagement: StateManagement,
    designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    const files: IGeneratedFile[] = [];

    const deps: Record<string, string> = {
      '@angular/animations': '^19.0.0',
      '@angular/common': '^19.0.0',
      '@angular/compiler': '^19.0.0',
      '@angular/core': '^19.0.0',
      '@angular/forms': '^19.0.0',
      '@angular/platform-browser': '^19.0.0',
      '@angular/platform-browser-dynamic': '^19.0.0',
      '@angular/router': '^19.0.0',
      rxjs: '^7.8.0',
      tslib: '^2.7.0',
      'zone.js': '^0.15.0',
    };
    const devDeps: Record<string, string> = {
      '@angular/cli': '^19.0.0',
      '@angular/compiler-cli': '^19.0.0',
      '@angular-devkit/build-angular': '^19.0.0',
      tailwindcss: '^4.0.0',
      postcss: '^8.4.0',
      autoprefixer: '^10.4.0',
    };
    files.push({
      path: 'package.json',
      content: this.createPackageJson(projectName, deps, devDeps),
    });

    files.push({
      path: 'tsconfig.json',
      content: JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2022',
            module: 'ES2022',
            moduleResolution: 'bundler',
            strict: true,
            noEmit: false,
            declaration: false,
            experimentalDecorators: true,
            lib: ['ES2022', 'DOM'],
            skipLibCheck: true,
            paths: { '@/*': ['./src/*'] },
          },
          angularCompilerOptions: {
            enableI18nLegacyMessageIdFormat: false,
            strictInjectionParameters: true,
            strictInputAccessModifiers: true,
            strictTemplates: true,
          },
        },
        null,
        2
      ),
    });

    files.push({
      path: 'angular.json',
      content: JSON.stringify(
        {
          $schema: './node_modules/@angular/cli/lib/config/schema.json',
          version: 1,
          newProjectRoot: 'projects',
          projects: {
            [projectName]: {
              projectType: 'application',
              root: '',
              sourceRoot: 'src',
              architect: {
                build: {
                  builder: '@angular-devkit/build-angular:application',
                  options: {
                    outputPath: `dist/${projectName}`,
                    index: 'src/index.html',
                    browser: 'src/main.ts',
                    tsConfig: 'tsconfig.json',
                    styles: ['src/styles.css'],
                  },
                },
                serve: {
                  builder: '@angular-devkit/build-angular:dev-server',
                },
              },
            },
          },
        },
        null,
        2
      ),
    });

    const primary = designContext.colorPalette?.primary ?? '#3b82f6';
    files.push({
      path: 'tailwind.config.ts',
      content: `import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: { primary: '${primary}' },
    },
  },
  plugins: [],
} satisfies Config;
`,
    });

    files.push({
      path: 'src/index.html',
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${projectName}</title>
  </head>
  <body>
    <app-root></app-root>
  </body>
</html>
`,
    });

    files.push({
      path: 'src/main.ts',
      content: `import { bootstrapApplication } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';

bootstrapApplication(AppComponent, {
  providers: [provideRouter(routes)],
}).catch((err) => console.error(err));
`,
    });

    files.push({
      path: 'src/styles.css',
      content: '@import "tailwindcss";\n',
    });

    files.push({
      path: 'src/app/app.component.ts',
      content: `import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: \`
    <div class="min-h-screen bg-background text-foreground">
      <router-outlet />
    </div>
  \`,
})
export class AppComponent {
  title = '${projectName}';
}
`,
    });

    files.push({
      path: 'src/app/app.routes.ts',
      content: `import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
];
`,
    });

    files.push({
      path: 'src/app/home/home.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  standalone: true,
  template: \`
    <main class="mx-auto max-w-4xl px-4 py-12">
      <h1 class="text-3xl font-bold tracking-tight">
        ${projectName}
      </h1>
      <p class="mt-2 text-muted-foreground">
        Angular project scaffolded by Siza.
      </p>
    </main>
  \`,
})
export class HomeComponent {}
`,
    });

    files.push({
      path: 'README.md',
      content: `# ${projectName}\n\nAngular 19 + TypeScript project generated by Siza.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n`,
    });

    this.logComplete('project', projectName, files.length);
    return files;
  }

  generateComponent(
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    // Test file
    files.push(this.createTestFile(componentName, componentType, designContext, componentLibrary));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return ['@radix-ui/themes', 'class-variance-authority'];
  }

  protected getRadixDependencies(): string[] {
    return ['@radix-ui/themes'];
  }

  protected getHeadlessUIDependencies(): string[] {
    return ['@headlessui/tailwindcss'];
  }

  protected getPrimeVueDependencies(): string[] {
    return [];
  }

  protected getMaterialDependencies(): string[] {
    return ['@angular/material'];
  }

  protected getShadcnImports(): string[] {
    return [];
  }

  protected getRadixImports(): string[] {
    return [];
  }

  protected getHeadlessUIImports(): string[] {
    return [];
  }

  protected getPrimeVueImports(): string[] {
    return [];
  }

  protected getMaterialImports(): string[] {
    return [];
  }

  protected generateShadcnComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4 bg-white rounded-lg shadow-md max-w-md">
      <h2 class="text-xl font-bold mb-2">${componentName}</h2>
      <p class="text-muted-foreground mb-4">A ${componentType.toLowerCase()} component using shadcn/ui styles</p>
      <button class="bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-2 rounded">Click me</button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  label = '${componentName}';
  isVisible = true;

  toggle(): void {
    this.isVisible = !this.isVisible;
  }
}`;
  }

  protected generateRadixComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="openDialog()" class="bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-2 rounded">${componentName}</button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black/50 flex items-center justify-center">
        <div class="bg-card p-6 rounded-lg shadow-lg border max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-muted-foreground mb-4">A ${componentType.toLowerCase()} component using Radix UI patterns</p>
          <button (click)="closeDialog()" class="bg-secondary text-secondary-foreground hover:bg-secondary/80 px-4 py-2 rounded">Close</button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  openDialog() {
    this.isDialogOpen = true;
  }

  closeDialog() {
    this.isDialogOpen = false;
  }
}`;
  }

  protected generateHeadlessUIComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="toggleDialog()" class="bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-2 rounded">${componentName}</button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black/50 flex items-center justify-center">
        <div class="bg-card p-6 rounded-lg shadow-lg border max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-muted-foreground mb-4">A ${componentType.toLowerCase()} component using Headless UI patterns</p>
          <button (click)="toggleDialog()" class="bg-secondary text-secondary-foreground hover:bg-secondary/80 px-4 py-2 rounded">Close</button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  toggleDialog() {
    this.isDialogOpen = !this.isDialogOpen;
  }
}`;
  }

  protected generatePrimeVueComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <button (click)="openDialog()" class="bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-2 rounded">
        <i class="fas fa-plus mr-2"></i>${componentName}
      </button>
      <div *ngIf="isDialogOpen" class="fixed inset-0 bg-black/50 flex items-center justify-center">
        <div class="bg-card p-6 rounded-lg shadow-lg border max-w-md">
          <h3 class="text-lg font-bold mb-2">${componentName}</h3>
          <p class="text-muted-foreground mb-4">A ${componentType.toLowerCase()} component using PrimeVue styles</p>
          <button (click)="closeDialog()" class="bg-secondary text-secondary-foreground hover:bg-secondary/80 px-4 py-2 rounded">
            <i class="fas fa-times mr-2"></i>Close
          </button>
        </div>
      </div>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  isDialogOpen = false;

  openDialog() {
    this.isDialogOpen = true;
  }

  closeDialog() {
    this.isDialogOpen = false;
  }
}`;
  }

  protected generateMaterialComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4">
      <mat-button (click)="openDialog()" color="primary" raised>${componentName}</mat-button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  constructor(private dialog: MatDialog) {}

  openDialog() {
    this.dialog.open(DialogContentComponent, {
      data: { title: '${componentName}', message: 'A ${componentType.toLowerCase()} component using Material Design' }
    });
  }
}

@Component({
  selector: 'dialog-content',
  template: \`
    <div class="bg-white p-6 rounded-lg">
      <h2 mat-dialog-title>{{ data.title }}</h2>
      <div mat-dialog-content>{{ data.message }}</div>
      <div mat-dialog-actions>
        <button mat-button (click)="dialogRef.close()">Close</button>
      </div>
    </div>
  \`
})
export class DialogContentComponent {
  constructor(public dialogRef: any) {}
}`;
  }

  protected generateTailwindComponent(componentType: string, _props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Component } from '@angular/core';

@Component({
  selector: 'app-${componentType}',
  template: \`
    <div class="p-4 bg-white rounded-lg shadow-md">
      <h2 class="text-xl font-bold mb-4">${componentName}</h2>
      <p class="text-muted-foreground mb-4">A ${componentType.toLowerCase()} component using Tailwind CSS</p>
      <button
        class="bg-primary text-primary-foreground hover:bg-primary/90 px-4 py-2 rounded"
        (click)="handleClick()"
      >
        Click me
      </button>
    </div>
  \`,
  styles: [\`
    :host {
      display: block;
    }
  \`]
})
export class ${componentName}Component {
  handleClick() {
    console.log('Button clicked');
  }
}`;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      content = this.generateComponentLibraryCode(componentType, props, componentLibrary);
    } else {
      content = this.generateTailwindComponent(componentType, props);
    }

    return {
      path: `src/app/components/${componentName}.component.ts`,
      content,
    };
  }

  private createTestFile(
    componentName: string,
    componentType: string,
    _designContext: IDesignContext,
    _componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    const content = `import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { ${componentName}Component } from './${componentName}.component';

describe('${componentName}Component', () => {
  let component: ${componentName}Component;
  let fixture: ComponentFixture<${componentName}Component>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [${componentName}Component]
    }).compileComponents();

    fixture = TestBed.createComponent(${componentName}Component);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should render component type', () => {
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.textContent).toContain('${componentType.toLowerCase()}');
  });
});
`;

    return {
      path: `src/app/components/${componentName}.component.spec.ts`,
      content,
    };
  }
}

// src/generators/react-generator.ts
import { BaseGenerator, ComponentLibrary } from './base-generator.js';
import type { IGeneratedFile, IDesignContext, Architecture, StateManagement, Framework } from '../types.js';
import { createLogger } from '../logger.js';

const _logger = createLogger('react-generator');

/**
 * React Generator - Generates React components and projects
 */
export class ReactGenerator extends BaseGenerator {
  constructor(framework: Framework) {
    super(framework);
  }

  /**
   * Generate a complete React project
   */
  generateProject(
    projectName: string,
    architecture: Architecture,
    stateManagement: StateManagement,
    designContext: IDesignContext
  ): IGeneratedFile[] {
    this.logStart('project', projectName);

    const files: IGeneratedFile[] = [];

    // Package.json
    files.push(this.createPackageJsonFile(projectName, stateManagement));

    // TypeScript config
    files.push(this.createTsConfigFile());

    // Vite config
    files.push(this.createViteConfigFile());

    // README
    files.push(this.createReadmeFile(projectName));

    // Main App component
    files.push(this.createAppComponent(designContext));

    // Index.html
    files.push(this.createIndexHtmlFile(projectName));

    // CSS/Tailwind config
    files.push(this.createTailwindConfig(designContext));

    // State management setup
    if (stateManagement !== 'none') {
      files.push(...this.createStateManagementFiles(stateManagement, designContext));
    }

    this.logComplete('project', projectName, files.length);
    return files;
  }

  /**
   * Generate a React component
   */
  generateComponent(
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile[] {
    this.logStart('component', componentType);

    const componentName = this.formatComponentName(componentType);
    const files: IGeneratedFile[] = [];

    // Component file
    files.push(this.createComponentFile(componentName, componentType, props, designContext, componentLibrary));

    // Storybook file (optional) - only when using component libraries
    if (process.env.NODE_ENV !== 'production' && componentLibrary && componentLibrary !== 'none') {
      files.push(this.createStorybookFile(componentName, componentType, designContext));
    }

    // Test file
    files.push(this.createTestFile(componentName, componentType, designContext));

    this.logComplete('component', componentType, files.length);
    return files;
  }

  private createPackageJsonFile(projectName: string, stateManagement: StateManagement): IGeneratedFile {
    const dependencies: Record<string, string> = {
      react: '^19.0.0',
      'react-dom': '^19.0.0',
      'react-router-dom': '^7.1.0',
      clsx: '^2.1.0',
    };

    const devDependencies: Record<string, string> = {
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      '@vitejs/plugin-react': '^4.3.0',
      vite: '^6.0.0',
      tailwindcss: '^4.0.0',
      autoprefixer: '^10.4.0',
      postcss: '^8.4.0',
      '@testing-library/react': '^16.1.0',
      '@testing-library/jest-dom': '^6.6.0',
      vitest: '^2.1.0',
    };

    // Add state management dependencies
    if (stateManagement === 'zustand') {
      dependencies.zustand = '^5.0.0';
    }

    return {
      path: 'package.json',
      content: this.createPackageJson(projectName, dependencies, devDependencies),
    };
  }

  private createTsConfigFile(): IGeneratedFile {
    return {
      path: 'tsconfig.json',
      content: this.createTsConfig(),
    };
  }

  private createViteConfigFile(): IGeneratedFile {
    return {
      path: 'vite.config.ts',
      content: this.createViteConfig(),
    };
  }

  private createReadmeFile(projectName: string): IGeneratedFile {
    return {
      path: 'README.md',
      content: this.createReadme(projectName),
    };
  }

  private createAppComponent(designContext: IDesignContext): IGeneratedFile {
    const content = `import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import './App.css';

function App() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '${designContext.colorPalette.background}' }}>
      <header className="p-6">
        <h1 className="text-3xl font-bold" style={{ color: '${designContext.colorPalette.primary}' }}>
          Welcome to ${designContext.typography.fontFamily}
        </h1>
      </header>
      <main className="container mx-auto px-4 py-8">
        <p style={{ color: '${designContext.colorPalette.foreground}' }}>
          Your React application is ready!
        </p>
      </main>
    </div>
  );
}

export default App;
`;

    return {
      path: 'src/App.tsx',
      content,
    };
  }

  private createIndexHtmlFile(projectName: string): IGeneratedFile {
    return {
      path: 'index.html',
      content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    };
  }

  private createTailwindConfig(designContext: IDesignContext): IGeneratedFile {
    return {
      path: 'tailwind.config.js',
      content: `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '${designContext.colorPalette.primary}',
        secondary: '${designContext.colorPalette.secondary}',
        background: '${designContext.colorPalette.background}',
        foreground: '${designContext.colorPalette.foreground}',
      },
      fontFamily: {
        sans: ['${designContext.typography.fontFamily}', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
`,
    };
  }

  private createStateManagementFiles(
    stateManagement: StateManagement,
    _designContext: IDesignContext
  ): IGeneratedFile[] {
    const files: IGeneratedFile[] = [];

    if (stateManagement === 'zustand') {
      files.push({
        path: 'src/store/useAppStore.ts',
        content: `import { create } from 'zustand';

interface AppState {
  count: number;
  increment: () => void;
  decrement: () => void;
}

export const useAppStore = create<AppState>((set) => ({
  count: 0,
  increment: () => set((state) => ({ count: state.count + 1 })),
  decrement: () => set((state) => ({ count: state.count - 1 })),
}));
`,
      });
    }

    return files;
  }

  private createComponentFile(
    componentName: string,
    componentType: string,
    props: Record<string, unknown>,
    designContext: IDesignContext,
    componentLibrary?: ComponentLibrary
  ): IGeneratedFile {
    const propsInterface =
      Object.keys(props).length > 0
        ? `interface ${componentName}Props {\n${Object.entries(props)
            .map(([key, type]) => `  ${key}: ${type};`)
            .join('\n')}\n}\n\n`
        : '';

    let content: string;

    if (componentLibrary && componentLibrary !== 'none') {
      // Use component library-specific generation
      const imports = this.getComponentLibraryImports(componentLibrary).join('\n');
      const componentCode = this.generateComponentLibraryCode(componentType, props, componentLibrary);

      content = `${propsInterface}${imports}

${componentCode}

export default ${componentName};`;
    } else {
      // Use default Tailwind CSS generation with appropriate HTML element
      const htmlElement = this.getHtmlElementForComponentType(componentType);
      const elementClasses = this.getTailwindClassesForComponentType(componentType);
      const rawComponentName = componentType.toLowerCase();

      content = `${propsInterface}import React from 'react';
import clsx from 'clsx';

export const ${rawComponentName}: React.FC<${rawComponentName}Props> = (${Object.keys(props).length > 0 ? '{' : ''}${Object.keys(props).join(', ')}${Object.keys(props).length > 0 ? '}' : ''}) => {
  return (
    <${htmlElement}
      className={clsx(
        '${elementClasses}'
      )}
      style={{
        backgroundColor: '${designContext.colorPalette.background}',
        color: '${designContext.colorPalette.foreground}',
        borderColor: '${designContext.colorPalette.muted}',
      }}
    >
      ${rawComponentName}
    </${htmlElement}>
  );
};

export default ${rawComponentName};`;
    }

    return {
      path: `src/components/${componentName}.tsx`,
      content,
    };
  }

  private createStorybookFile(
    componentName: string,
    _componentType: string,
    _designContext: IDesignContext
  ): IGeneratedFile {
    const content = `import type { Meta, StoryObj } from '@storybook/react';
import { ${componentName} } from './${componentName}';

const meta: Meta<typeof ${componentName}> = {
  title: 'Components/${componentName}',
  component: ${componentName},
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {},
};

export const WithCustomProps: Story = {
  args: {
    // Add custom props here
  },
};
`;

    return {
      path: `src/components/${componentName}.stories.tsx`,
      content,
    };
  }

  private createTestFile(componentName: string, componentType: string, _designContext: IDesignContext): IGeneratedFile {
    const content = `import { render, screen } from '@testing-library/react';
import { ${componentName} } from './${componentName}';

describe('${componentName}', () => {
  it('renders without crashing', () => {
    render(<${componentName} />);
    expect(screen.getByText('${componentName}')).toBeInTheDocument();
  });

  it('displays the component type', () => {
    render(<${componentName} />);
    expect(screen.getByText(/${componentType}/i)).toBeInTheDocument();
  });
});
`;

    return {
      path: `src/components/${componentName}.test.tsx`,
      content,
    };
  }

  // Component Library Implementation Methods

  protected getShadcnDependencies(): string[] {
    return [
      '@radix-ui/react-slot',
      '@radix-ui/react-dialog',
      '@radix-ui/react-dropdown-menu',
      '@radix-ui/react-select',
      '@radix-ui/react-tabs',
      '@radix-ui/react-toast',
      'class-variance-authority',
      'clsx',
      'tailwind-merge',
      'lucide-react',
    ];
  }

  protected getRadixDependencies(): string[] {
    return [
      '@radix-ui/react-slot',
      '@radix-ui/react-dialog',
      '@radix-ui/react-dropdown-menu',
      '@radix-ui/react-select',
      '@radix-ui/react-tabs',
      '@radix-ui/react-toast',
    ];
  }

  protected getHeadlessUIDependencies(): string[] {
    return ['@headlessui/react', '@heroicons/react'];
  }

  protected getPrimeVueDependencies(): string[] {
    return ['primevue', 'primeicons'];
  }

  protected getMaterialDependencies(): string[] {
    return ['@mui/material', '@mui/icons-material'];
  }

  protected getShadcnImports(): string[] {
    return [
      'import { cn } from "lib/utils";',
      'import { Button } from "components/ui/button";',
      'import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "components/ui/card";',
      'import { Input } from "components/ui/input";',
      'import { Label } from "components/ui/label";',
    ];
  }

  protected getRadixImports(): string[] {
    return [
      'import * as Dialog from "@radix-ui/react-dialog";',
      'import * as DropdownMenu from "@radix-ui/react-dropdown-menu";',
      'import * as Select from "@radix-ui/react-select";',
      'import * as Tabs from "@radix-ui/react-tabs";',
    ];
  }

  protected getHeadlessUIImports(): string[] {
    return [
      'import { Button } from "@headlessui/react";',
      'import { Dialog } from "@headlessui/react";',
      'import { Menu } from "@headlessui/react";',
      'import { Transition } from "@headlessui/react";',
    ];
  }

  protected getPrimeVueImports(): string[] {
    return [
      'import Button from "primevue/button";',
      'import Dialog from "primevue/dialog";',
      'import InputText from "primevue/inputtext";',
      'import DataTable from "primevue/datatable";',
    ];
  }

  protected getMaterialImports(): string[] {
    return [
      'import Button from "@mui/material/Button";',
      'import Dialog from "@mui/material/Dialog";',
      'import TextField from "@mui/material/TextField";',
      'import Card from "@mui/material/Card";',
      'import CardContent from "@mui/material/CardContent";',
    ];
  }

  protected generateShadcnComponent(componentType: string, props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <Card className={cn("w-full max-w-md", props.className)}>
      <CardHeader>
        <CardTitle>${componentName}</CardTitle>
        <CardDescription>
          A ${componentType.toLowerCase()} component built with shadcn/ui
        </CardDescription>
      </CardHeader>
      <CardContent>
        <p>This is a ${componentType.toLowerCase()} component using shadcn/ui design system.</p>
        <Button className="mt-4">Click me</Button>
      </CardContent>
    </Card>
  )
}`;
  }

  protected generateRadixComponent(componentType: string, props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);
    const type = componentType.toLowerCase();

    if (type === 'button') {
      return `import * as React from "react"
import { Slot } from "@radix-ui/react-slot"

interface ${componentName}Props extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  asChild?: boolean
}

export const ${componentName} = React.forwardRef<HTMLButtonElement, ${componentName}Props>(
  ({ asChild, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return <Comp ref={ref} {...props} />
  }
)
${componentName}.displayName = "${componentName}"

export function ${componentName}Demo() {
  return <Button>${componentName}</Button>
}`;
    }

    if (type === 'dialog') {
      return `import * as Dialog from "@radix-ui/react-dialog"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <Dialog.Root>
      <Dialog.Trigger asChild>
        <button>Open ${componentName}</button>
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 bg-black/50" />
        <Dialog.Content className="fixed left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white p-6 rounded-lg shadow-lg">
          <Dialog.Title>${componentName}</Dialog.Title>
          <Dialog.Description>
            A ${componentType.toLowerCase()} component using Radix UI primitives
          </Dialog.Description>
          <Dialog.Close asChild>
            <button>Close</button>
          </Dialog.Close>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}`;
    }

    return `import * as React from "react"
import { Slot } from "@radix-ui/react-slot"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <div className="${type}-root">
      <span>${componentName}</span>
    </div>
  )
}`;
  }

  protected generateHeadlessUIComponent(componentType: string, props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import { Button } from "@headlessui/react"
import { Dialog } from "@headlessui/react"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <div className="p-4">
      <Button onClick={() => {}}>${componentName}</Button>
      <Dialog open={false} onClose={() => {}}>
        <Dialog.Panel className="fixed inset-0 bg-white p-6 rounded-lg shadow-lg">
          <Dialog.Title>${componentName}</Dialog.Title>
          <Dialog.Description>
            A ${componentType.toLowerCase()} component using Headless UI
          </Dialog.Description>
          <div className="mt-4">
            <Button onClick={() => {}}>Close</Button>
          </div>
        </Dialog.Panel>
      </Dialog>
    </div>
  )
}`;
  }

  protected generatePrimeVueComponent(componentType: string, props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    // Note: This would be used in a Vue generator, but we provide a React-compatible version
    return `import { Button } from "@headlessui/react"
import { Dialog } from "@headlessui/react"

export function ${componentName}(${this.generatePropsInterface(props)}) {
  const [open, setOpen] = React.useState(false)

  return (
    <div className="p-4">
      <Button onClick={() => setOpen(true)}>${componentName}</Button>
      <Dialog open={open} onClose={() => setOpen(false)}>
        <Dialog.Panel className="fixed inset-0 bg-white p-6 rounded-lg shadow-lg">
          <Dialog.Title>${componentName}</Dialog.Title>
          <Dialog.Description>
            A ${componentType.toLowerCase()} component (PrimeVue style)
          </Dialog.Description>
          <div className="mt-4">
            <Button onClick={() => setOpen(false)}>Close</Button>
          </div>
        </Dialog.Panel>
      </Dialog>
    </div>
  )
}`;
  }

  protected generateMaterialComponent(componentType: string, props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `import Button from '@mui/material/Button'
import Dialog from '@mui/material/Dialog'
import DialogTitle from '@mui/material/DialogTitle'
import DialogContent from '@mui/material/DialogContent'
import DialogActions from '@mui/material/DialogActions'

export function ${componentName}(${this.generatePropsInterface(props)}) {
  const [open, setOpen] = React.useState(false)

  return (
    <div className="p-4">
      <Button variant="contained" onClick={() => setOpen(true)}>
        ${componentName}
      </Button>
      <Dialog open={open} onClose={() => setOpen(false)}>
        <DialogTitle>${componentName}</DialogTitle>
        <DialogContent>
          <p>A ${componentType.toLowerCase()} component using Material UI</p>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>
    </div>
  )
}`;
  }

  protected generateTailwindComponent(componentType: string, props: Record<string, unknown>): string {
    const componentName = this.formatComponentName(componentType);

    return `export function ${componentName}(${this.generatePropsInterface(props)}) {
  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h2 className="text-xl font-bold mb-4">${componentName}</h2>
      <p className="text-gray-600 mb-4">
        A ${componentType.toLowerCase()} component using Tailwind CSS
      </p>
      <button
        className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded"
        onClick={() => console.log('Button clicked')}
      >
        Click me
      </button>
    </div>
  )
}`;
  }

  private generatePropsInterface(props: Record<string, unknown>): string {
    const propKeys = Object.keys(props);
    if (propKeys.length === 0) return '';

    const propDefinitions = propKeys
      .map((key) => {
        const value = props[key];
        let type = 'string';

        if (typeof value === 'boolean') type = 'boolean';
        else if (typeof value === 'number') type = 'number';
        else if (typeof value === 'object') type = 'any';

        return `${key}?: ${type}`;
      })
      .join(', ');

    return `{ ${propDefinitions} }`;
  }

  private getHtmlElementForComponentType(componentType: string): string {
    const elementMap: Record<string, string> = {
      button: 'button',
      input: 'input',
      card: 'div',
      dialog: 'dialog',
      modal: 'dialog',
      form: 'form',
      nav: 'nav',
      header: 'header',
      footer: 'footer',
      section: 'section',
      article: 'article',
      aside: 'aside',
      main: 'main',
      img: 'img',
      link: 'a',
      text: 'p',
      heading: 'h2',
      list: 'ul',
      listItem: 'li',
      table: 'table',
      row: 'tr',
      cell: 'td',
    };

    return elementMap[componentType.toLowerCase()] || 'div';
  }

  private getTailwindClassesForComponentType(componentType: string): string {
    const classMap: Record<string, string> = {
      button: 'px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors',
      input: 'px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500',
      card: 'p-4 rounded-lg bg-white shadow-md border border-gray-200',
      dialog: 'p-6 rounded-lg bg-white shadow-lg border border-gray-200',
      modal: 'fixed inset-0 flex items-center justify-center bg-black bg-opacity-50',
      form: 'space-y-4',
      nav: 'flex space-x-4',
      header: 'pb-4 border-b border-gray-200',
      footer: 'pt-4 border-t border-gray-200',
      section: 'py-8',
      article: 'prose max-w-none',
      aside: 'w-64',
      main: 'flex-1',
      img: 'max-w-full h-auto',
      link: 'text-blue-500 hover:text-blue-700 underline',
      text: 'text-gray-700',
      heading: 'text-2xl font-bold mb-4',
      list: 'list-disc list-inside space-y-2',
      listItem: 'ml-4',
      table: 'w-full border-collapse',
      row: 'border-b',
      cell: 'px-4 py-2 border',
    };

    return classMap[componentType.toLowerCase()] || 'p-4';
  }
}
